# Generated by Django 2.2.1 on 2019-05-06 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crush',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=50)),
                ('data', models.DateField()),
                ('signo', models.CharField(choices=[('ar', 'Áries'), ('tr', 'Touro'), ('gm', 'Gêmeos'), ('cr', 'Câncer'), ('le', 'Leão'), ('vr', 'Virgem'), ('lb', 'Libra'), ('es', 'Escorpião'), ('sp', 'Serpentário'), ('sg', 'Sargitário'), ('cp', 'Capricórnio'), ('aq', 'Aquário'), ('px', 'Peixes')], max_length=2)),
                ('qualidade', models.CharField(max_length=100)),
                ('defeito', models.CharField(default='Não está comigo', max_length=100)),
                ('reciproco', models.BooleanField(default=False)),
                ('solteiro', models.BooleanField(default=False)),
            ],
        ),
    ]
